version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: authapp_postgres_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d authapp"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authapp_backend_dev
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=authapp;Username=postgres;Password=postgres
      - JwtSettings__Key=super_secret_jwt_key_1234567890123_dev
      - JwtSettings__Issuer=AuthApp
      - JwtSettings__Audience=AuthAppUsers
      - JwtSettings__ExpirationInMinutes=60
      - CORS__AllowedOrigins=http://localhost:3000

volumes:
  postgres_data:
